---
# tasks file for common-packages
- name: Install common packages
  become: yes
  ansible.builtin.apt:
    pkg:
    - neofetch
    - net-tools
    - curl
    - wget
    - python3
    - htop
    - python-pip
    - unzip
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg
    - gnupg2
    
  tags:
    - common-packages
...