---
# Update all packages
- name: Update and Upgrade
  become: yes
  ansible.builtin.apt:
    name: "*"
    state: latest
  tags:
    - common-packages

#Upgrade the OS
- name: Upgrade the OS (apt-get dist-upgrade)
  become: yes
  ansible.builtin.apt:
    upgrade: dist
  tags:
    - common-packages

# Install common packages
- name: Install common packages
  become: yes
  ansible.builtin.apt:
    pkg:
    - neofetch
    - net-tools
    - curl
    - wget
    - python3
    - htop
    - python-pip
    - unzip
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg2
    
  tags:
    - common-packages
...