---
# Install server packages
- name: Install server packages
  become: yes
  ansible.builtin.apt:
    pkg:
    - cockpit
    - rsync
    - vsftpd
    - virtualenv
    - python3-setuptools
    - apt-transport-https
    - ca-certificates
    - curl
    - wget
    - gnupg2
  tags:
    - server-packages
...