---
- hosts: all
  tasks:
    - set_fact:
        dist: "{{ ansible_distribution | lower }}"
        major_ver: "{{ ansible_distribution_version.split('.')[0] }}"
        arch: "{{ ansible_architecture }}"
    - set_fact:
        dist_ver: "{{ dist }}_{{ major_ver }}"
        dist_ver_arch: "{{ dist }}_{{ major_ver }}_{{ arch }}"
    - group_by:
        key: "os_{{ dist }}"
    - group_by:
        key: "os_{{ dist_ver }}"
    - group_by:
        key: "os_{{ dist_ver_arch }}"
  tags:
  - always
  
- hosts: all
  roles:
  - role: common-packages


...

